import {
  TRIBES,
  SKIN_COLORS,
  FUR_COLORS,
  EYE_COLORS,
  PUPIL_COLORS,
  HAIR,
  MOUTHS,
  BEARDS,
  TOPS,
  OUTERWEAR,
  PRINTS,
  BOTTOMS,
  FOOTWEAR,
  BELTS,
  HATS,
  EYEWEAR,
  PIERCINGS,
  WRISTS,
  HANDS,
  NECKWEAR,
  LEFT_ITEMS,
  RIGHT_ITEMS,
  BACKGROUNDS,
} from '../../constants/characters';

export const PAGE_SIZE = 50;

export const INITIAL_FILTER_STATE = {
  tribes: [],
  price: {
    low: undefined,
    high: undefined,
  },
  totalMultiplier: {
    low: undefined,
    high: undefined,
  },
  numOfRentals: {
    low: undefined,
    high: undefined,
  },
  backgrounds: [],
  skinColors: [],
  furColors: [],
  eyeColors: [],
  pupilColors: [],
  hair: [],
  mouths: [],
  beards: [],
  tops: [],
  outerwear: [],
  prints: [],
  bottoms: [],
  footwear: [],
  belts: [],
  hats: [],
  eyewear: [],
  piercings: [],
  wrists: [],
  hands: [],
  neckwear: [],
  leftItems: [],
  rightItems: [],
};

export const FILTER_STATE_MAPPING = {
  tribes: TRIBES,
  backgrounds: BACKGROUNDS,
  skinColors: SKIN_COLORS,
  furColors: FUR_COLORS,
  eyeColors: EYE_COLORS,
  pupilColors: PUPIL_COLORS,
  hair: HAIR,
  mouths: MOUTHS,
  beards: BEARDS,
  tops: TOPS,
  outerwear: OUTERWEAR,
  prints: PRINTS,
  bottoms: BOTTOMS,
  footwear: FOOTWEAR,
  belts: BELTS,
  hats: HATS,
  eyewear: EYEWEAR,
  piercings: PIERCINGS,
  wrists: WRISTS,
  hands: HANDS,
  neckwear: NECKWEAR,
  leftItems: LEFT_ITEMS,
  rightItems: RIGHT_ITEMS,
};

export const FILTER_LABEL_MAPPING = {
  backgrounds: 'Background',
  skinColors: 'Skin Colors',
  furColors: 'Fur Colors',
  eyeColors: 'Eye Colors',
  pupilColors: 'Pupil Colors',
  hair: 'Hair',
  mouths: 'Mouths',
  beards: 'Beards',
  tops: 'Tops',
  outerwear: 'Outerwear',
  prints: 'Prints',
  bottoms: 'Bottoms',
  footwear: 'Footwear',
  belts: 'Belts',
  hats: 'Hats',
  eyewear: 'Eyewear',
  piercings: 'Piercings',
  wrists: 'Wrists',
  hands: 'Hands',
  neckwear: 'Neckwear',
  leftItems: 'Left Items',
  rightItems: 'Right Items',
};

export const FILTER_STATE_KEY_TO_INDEX = {
  tribes: 0,
  skinColors: 1,
  furColors: 2,
  eyeColors: 3,
  pupilColors: 4,
  hair: 5,
  mouths: 6,
  beards: 7,
  tops: 8,
  outerwear: 9,
  prints: 10,
  bottoms: 11,
  footwear: 12,
  belts: 13,
  hats: 14,
  eyewear: 15,
  piercings: 16,
  wrists: 17,
  hands: 18,
  neckwear: 19,
  leftItems: 20,
  rightItems: 21,
};
