const ITEM_HEIGHT = 48;
const ITEM_PADDING_TOP = 8;
export const MenuProps = {
  PaperProps: {
    style: {
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
      width: 250,
    },
  },
};

export const PAGE_SIZE = 50;

export const INITIAL_FILTER_STATE = {
  tribes: [],
  skinColors: [],
  furColors: [],
  eyeColors: [],
  pupilColors: [],
  hair: [],
  mouths: [],
  beards: [],
  facemarks: [],
  misc: [],
  tops: [],
  outerwear: [],
  prints: [],
  bottoms: [],
  footwear: [],
  belts: [],
  hats: [],
  eyewear: [],
  piercings: [],
  wrists: [],
  hands: [],
  neckwear: [],
  leftItems: [],
  rightItems: [],
};

export const TRAIT_NAME_MAP = {
  tribe: "Tribe",
  skinColor: "Skin Color",
  furColor: "Fur Color",
  eyeColor: "Eyes",
  pupilColor: "Pupil",
  hair: "Hair",
  mouth: "Mouth",
  beard: "Beard",
  facemark: "Facemark",
  misc: "Misc.",
  top: "Top",
  outerwear: "Outerwear",
  print: "Print",
  bottom: "Bottom",
  footwear: "Footwear",
  belt: "Belt",
  hat: "Hat",
  eyewear: "Eyewear",
  piercings: "Piercings",
  wrists: "Wrists",
  hands: "Hands",
  neckwear: "Neckwear",
  leftItem: "Left Item",
  rightItem: "Right Item",
};

export const TRIBES = {
  1: "Ape",
  2: "Human",
  3: "Doge",
  4: "Frog",
  5: "Cat",
  6: "Alien",
};
export const SKIN_COLORS = {
  // Ape
  15: "Single Origin Ape",
  16: "Toledo Ape",
  17: "Latin Charm Ape",
  18: "Baleine Blue Ape",
  19: "Ornery Tangerine Ape",
  20: "Nordic Ape",
  21: "Seance Ape",
  22: "White Ape",
  23: "Sparky Blue Ape",
  24: "Atmosphere Ape",
  25: "Primrose Path Ape",
  26: "River Styx Ape",
  // Human
  27: "Gentle Doe Human",
  28: "Sweet Curry Human",
  29: "Iced Tea Human",
  30: "Single Origin Human",
  31: "Toledo Human",
  32: "Primrose Path Human",
  33: "Atmosphere Human",
  // Doge
  34: "Ripe Pumpkin Doge",
  35: "Ornery Tangerine Doge",
  36: "Baleine Blue Doge",
  37: "Allegiance Doge",
  38: "Toledo Doge",
  39: "Latin Charm Doge",
  40: "Primrose Path Doge",
  41: "Cherry Soda Doge",
  // Frog
  42: "Range Land Frog",
  43: "White Frog",
  44: "Seance Frog",
  45: "Baleine Blue Frog",
  46: "Ripe Pumpkin Frog",
  47: "Cherry Soda Frog",
  48: "Allegiance Frog",
  49: "Sparky Blue Frog",
  50: "Atmosphere Frog",
  51: "Begonia Frog",
  52: "Greenery Frog",
  // Cat
  53: "Icy Brook Cat",
  54: "Signal Pink Cat",
  55: "Ripe Pumpkin Cat",
  56: "Baleine Blue Cat",
  57: "Bonne Nuit Cat",
  58: "Sweet Curry Cat",
  59: "Greenery Cat",
  60: "Atmosphere Cat",
  61: "Primrose Path Cat",
  62: "White Cat",
  63: "River Styx Cat",
  // Alien
  64: "Range Land Alien",
  65: "White Alien",
  66: "Seance Alien",
  67: "Baleine Blue Alien",
  68: "Ripe Pumpkin Alien",
  69: "Gentle Doe Alien",
  70: "Allegiance Alien",
  71: "Atmosphere Alien",
  72: "Sparky Blue Alien",
  73: "Cherry Soda Alien",
  74: "Begonia Alien",
};
export const FUR_COLORS = {
  // Ape
  75: "Sweet Curry Ape Fur",
  76: "Iced Tea Ape Fur",
  77: "Blueberry Buckle Ape Fur",
  78: "Allegiance Ape Fur",
  79: "Gentle Doe Ape Fur",
  80: "Pink Macaroon Ape Fur",
  81: "Signal Pink Ape Fur",
  82: "White Ape Fur",
  83: "Sparky Blue Ape Fur",
  84: "Atmosphere Ape Fur",
  85: "Primrose Path Ape Fur",
  86: "Icy Brook Ape Fur",
  // Human
  // Doge
  87: "White Doge Fur",
  88: "Pink Macaroon Doge Fur",
  89: "Icy Brook Doge Fur",
  90: "Blueberry Buckle Doge Fur",
  91: "Sweet Curry Doge Fur",
  92: "Bonne Nuit Doge Fur",
  93: "Allegiance Doge Fur",
  94: "Latin Charm Doge Fur",
  // Frog
  // Cat
  95: "White Cat Fur",
  96: "Bonne Nuit Cat Fur",
  97: "Toledo Cat Fur",
  98: "Ripe Pumpkin Cat Fur",
  99: "Ornery Tangerine Cat Fur",
  100: "Sweet Curry Cat Fur",
  101: "Gentle Doe Cat Fur",
  102: "Allegiance Cat Fur",
  103: "Icy Brook Cat Fur",
  104: "Primrose Path Cat Fur",
  105: "Sparky Blue Cat Fur",
  // Alien
};
export const EYE_COLORS = {
  106: "White Eyes",
  107: "River Styx Eyes",
  108: "Sparky Blue Eyes",
  109: "Atmosphere Eyes",
  110: "Latin Charm Eyes",
  111: "Bonne Nuit Eyes",
  112: "Primrose Path Eyes",
  113: "Cherry Soda Eyes",
  114: "Icy Brook Eyes",
};
export const PUPIL_COLORS = {
  115: "River Styx Pupils",
  116: "Cherry Soda Pupils",
  117: "Japanese Carmine Pupils",
  118: "Atmosphere Pupils",
  119: "Range Land Pupils",
  120: "Bonne Nuit Pupils",
  121: "Sparky Blue Pupils",
  122: "Primrose Path Pupils",
  123: "White Pupils",
};
export const HAIR = {
  200: "Hair Afro",
  201: "Hair Bangs",
  202: "Hair Bun",
  203: "Hair Buzzcut",
  204: "Hair Curly",
  205: "Hair High Flat Top",
  206: "Hair Long",
  207: "Hair Mohavk",
  208: "Hair Pigtails",
  209: "Hair Ponytail",
  210: "Hair Pulled Back",
  211: "Hair Shaggy",
  212: "Hair Simple",
  213: "Hair Spiky",
  214: "Hair Straight",
};
export const MOUTHS = {
  215: "Cigarette",
  216: "Mask",
  217: "Pipe",
};
export const BEARDS = {
  218: "Circle Beard",
  219: "Curtain",
  220: "Goatee",
  221: "Handlebar",
  222: "Huge Beard",
  223: "Huge Mustache",
  224: "Mustache",
  225: "Mutton",
  226: "Van Dyke",
};
export const FACEMARKS = { 227: "Scar 01" };
export const MISC = { 228: "Headband", 229: "Ninja Mask" };
export const TOPS = {
  230: "Bra",
  231: "Crop Top",
  232: "Longsleeve",
  233: "Longsleeve Buttonup",
  234: "Longsleeve Collared",
  235: "Tshirt",
  236: "Tshirt Collared",
  237: "Vest",
  238: "Vest Torn",
};
export const OUTERWEAR = {
  239: "Dinner Jacket Open",
  240: "Hoodie",
  241: "Jacket Closed",
  242: "Jacket Elbowpatches Open",
  243: "Jacket Open",
  244: "Overalls",
  245: "Prisoners Robe",
  246: "Waistcoat",
};
export const PRINTS = {
  247: "Banana",
  248: "Beer",
  249: "Bomb",
  250: "Burger",
  251: "Cactus",
  252: "Carrot",
  253: "Duck",
  254: "Heart",
  255: "Ice Cream",
  256: "Moon",
  257: "Number 15",
  258: "Number One",
  259: "Rock",
  260: "Skull",
  261: "Smile",
  262: "Sun",
};
export const BOTTOMS = {
  263: "Boxers",
  264: "Boxers Dotty",
  265: "Boxers Striped",
  266: "Briefs",
  267: "Dark Pants",
  268: "G String",
  269: "Jeans",
  270: "Jeans Kneepads",
  271: "Jorts",
  272: "Jorts Frayed",
  273: "Skirt",
  274: "Vertical Stripe Pants",
};
export const FOOTWEAR = {
  275: "Shoes",
  276: "Shoes Basic",
  277: "Shoes Duck Faces",
  278: "Shoes Space Boots",
  279: "Shoes Work Boots",
};
export const BELTS = { 280: "Belt Simple" };
export const HATS = {
  281: "Baseball Cap",
  282: "Beanie",
  283: "Bowler Hat",
  284: "Construction Helmet",
  285: "Cowboy Hat",
  286: "Crown",
  287: "Fish Hat",
  288: "Hamburger",
  289: "Helmet Viking",
  290: "Kid Propeller Hat",
  291: "Party Hat",
  292: "Pirate Hat",
  293: "Police Hat",
  294: "Santa Hat",
  295: "Sombrero",
  296: "Top Hat",
  297: "Traffic Cone",
};
export const EYEWEAR = {
  298: "Broken Glasses",
  299: "Cyborg",
  300: "Eyepatch",
  301: "Eyepatch Skull",
  302: "Goggles Vr",
  303: "Monacle",
  304: "Party Glasses",
  305: "Rectangular Glasses",
  306: "Steampunk Goggles",
  307: "Sunglasses 01",
  308: "Sunglasses 02",
  309: "Sunglasses 03",
  310: "Sunglasses 04",
  311: "Visor",
};
export const PIERCINGS = { 312: "Earring" };
export const WRISTS = { 313: "Watch" };
export const HANDS = { 314: "Gloves", 315: "Gloves Cooking" };
export const NECKWEAR = { 316: "Bowtie", 317: "Necklace Gold", 318: "Tie" };
export const LEFT_ITEMS = { 319: "Hold Left Briefcase", 320: "Hold Left Dynamite" };
export const RIGHT_ITEMS = { 321: "Hold Right Cutlass", 322: "Hold Right Sword" };

export const TRAIT_VALUE_MAP = {
  ...TRIBES,
  ...SKIN_COLORS,
  ...FUR_COLORS,
  ...EYE_COLORS,
  ...PUPIL_COLORS,
  ...HAIR,
  ...MOUTHS,
  ...BEARDS,
  ...FACEMARKS,
  ...MISC,
  ...TOPS,
  ...OUTERWEAR,
  ...PRINTS,
  ...BOTTOMS,
  ...FOOTWEAR,
  ...BELTS,
  ...HATS,
  ...EYEWEAR,
  ...PIERCINGS,
  ...WRISTS,
  ...HANDS,
  ...NECKWEAR,
  ...LEFT_ITEMS,
  ...RIGHT_ITEMS,
};

export const FILTER_STATE_MAPPING = {
  tribes: TRIBES,
  skinColors: SKIN_COLORS,
  furColors: FUR_COLORS,
  eyeColors: EYE_COLORS,
  pupilColors: PUPIL_COLORS,
  hair: HAIR,
  mouths: MOUTHS,
  beards: BEARDS,
  facemarks: FACEMARKS,
  misc: MISC,
  tops: TOPS,
  outerwear: OUTERWEAR,
  prints: PRINTS,
  bottoms: BOTTOMS,
  footwear: FOOTWEAR,
  belts: BELTS,
  hats: HATS,
  eyewear: EYEWEAR,
  piercings: PIERCINGS,
  wrists: WRISTS,
  hands: HANDS,
  neckwear: NECKWEAR,
  leftItems: LEFT_ITEMS,
  rightItems: RIGHT_ITEMS,
};
