const CHARACTER_TRAIT_TYPES = [
  "Tribe",
  "Skin Color",
  "Fur Color",
  "Eye Color",
  "Pupil Color",
  "Hair",
  "Mouth",
  "Beard",
  "Facemark",
  "Misc",
  "Top",
  "Outerwear",
  "Print",
  "Bottom",
  "Footwear",
  "Belt",
  "Hat",
  "Eyewear",
  "Piercings",
  "Wrists",
  "Hands",
  "Neckwear",
  "Left Item",
  "Right Item",
];

const TRIBES = {
  1: "Ape",
  2: "Human",
  3: "Doge",
  4: "Frog",
  5: "Cat",
  6: "Alien",
};
const SKIN_COLORS = {
  // Ape
  15: "Single Origin Ape",
  16: "Toledo Ape",
  17: "Latin Charm Ape",
  18: "Baleine Blue Ape",
  19: "Ornery Tangerine Ape",
  20: "Nordic Ape",
  21: "Seance Ape",
  22: "White Ape",
  23: "Sparky Blue Ape",
  24: "Atmosphere Ape",
  25: "Primrose Path Ape",
  26: "River Styx Ape",
  // Human
  27: "Gentle Doe Human",
  28: "Sweet Curry Human",
  29: "Iced Tea Human",
  30: "Single Origin Human",
  31: "Toledo Human",
  32: "Primrose Path Human",
  33: "Atmosphere Human",
  // Doge
  34: "Ripe Pumpkin Doge",
  35: "Ornery Tangerine Doge",
  36: "Baleine Blue Doge",
  37: "Allegiance Doge",
  38: "Toledo Doge",
  39: "Latin Charm Doge",
  40: "Primrose Path Doge",
  41: "Cherry Soda Doge",
  // Frog
  42: "Range Land Frog",
  43: "White Frog",
  44: "Seance Frog",
  45: "Baleine Blue Frog",
  46: "Ripe Pumpkin Frog",
  47: "Cherry Soda Frog",
  48: "Allegiance Frog",
  49: "Sparky Blue Frog",
  50: "Atmosphere Frog",
  51: "Begonia Frog",
  52: "Greenery Frog",
  // Cat
  53: "Icy Brook Cat",
  54: "Signal Pink Cat",
  55: "Ripe Pumpkin Cat",
  56: "Baleine Blue Cat",
  57: "Bonne Nuit Cat",
  58: "Sweet Curry Cat",
  59: "Greenery Cat",
  60: "Atmosphere Cat",
  61: "Primrose Path Cat",
  62: "White Cat",
  63: "River Styx Cat",
  // Alien
  64: "Range Land Alien",
  65: "White Alien",
  66: "Seance Alien",
  67: "Baleine Blue Alien",
  68: "Ripe Pumpkin Alien",
  69: "Gentle Doe Alien",
  70: "Allegiance Alien",
  71: "Atmosphere Alien",
  72: "Sparky Blue Alien",
  73: "Cherry Soda Alien",
  74: "Begonia Alien",
};
const FUR_COLORS = {
  // Ape
  75: "Sweet Curry Ape Fur",
  76: "Iced Tea Ape Fur",
  77: "Blueberry Buckle Ape Fur",
  78: "Allegiance Ape Fur",
  79: "Gentle Doe Ape Fur",
  80: "Canary Island Ape Fur",
  81: "Signal Pink Ape Fur",
  82: "White Ape Fur",
  83: "Sparky Blue Ape Fur",
  84: "Atmosphere Ape Fur",
  85: "Primrose Path Ape Fur",
  86: "Icy Brook Ape Fur",
  // Human
  // Doge
  87: "White Doge Fur",
  88: "Canary Island Doge Fur",
  89: "Icy Brook Doge Fur",
  90: "Blueberry Buckle Doge Fur",
  91: "Sweet Curry Doge Fur",
  92: "Bonne Nuit Doge Fur",
  93: "Allegiance Doge Fur",
  94: "Latin Charm Doge Fur",
  // Frog
  // Cat
  95: "White Cat Fur",
  96: "Bonne Nuit Cat Fur",
  97: "Toledo Cat Fur",
  98: "Ripe Pumpkin Cat Fur",
  99: "Ornery Tangerine Cat Fur",
  100: "Sweet Curry Cat Fur",
  101: "Gentle Doe Cat Fur",
  102: "Allegiance Cat Fur",
  103: "Icy Brook Cat Fur",
  104: "Primrose Path Cat Fur",
  105: "Sparky Blue Cat Fur",
  // Alien
};
const EYE_COLORS = {
  106: "White Eyes",
  107: "River Styx Eyes",
  108: "Sparky Blue Eyes",
  109: "Atmosphere Eyes",
  110: "Latin Charm Eyes",
  111: "Bonne Nuit Eyes",
  112: "Primrose Path Eyes",
  113: "Cherry Soda Eyes",
  114: "Icy Brook Eyes",
};
const PUPIL_COLORS = {
  115: "River Styx Pupils",
  116: "Cherry Soda Pupils",
  117: "Japanese Carmine Pupils",
  118: "Atmosphere Pupils",
  119: "Range Land Pupils",
  120: "Bonne Nuit Pupils",
  121: "Sparky Blue Pupils",
  122: "Primrose Path Pupils",
  123: "White Pupils",
};
const HAIR = {
  200: "Hair Afro",
  201: "Hair Bangs",
  202: "Hair Bun",
  203: "Hair Buzzcut",
  204: "Hair Curly",
  205: "Hair High Flat Top",
  206: "Hair Long",
  207: "Hair Mohavk",
  208: "Hair Pigtails",
  209: "Hair Ponytail",
  210: "Hair Pulled Back",
  211: "Hair Shaggy",
  212: "Hair Simple",
  213: "Hair Spiky",
  214: "Hair Straight",
};
const MOUTHS = {
  215: "Cigarette",
  216: "Mask",
  217: "Pipe",
};
const BEARDS = {
  218: "Circle Beard",
  219: "Curtain",
  220: "Goatee",
  221: "Handlebar",
  222: "Huge Beard",
  223: "Huge Mustache",
  224: "Mustache",
  225: "Mutton",
  226: "Van Dyke",
};
const FACEMARKS = { 227: "Scar 01" };
const MISC = { 228: "Headband", 229: "Ninja Mask" };
const TOPS = {
  230: "Bra",
  231: "Crop Top",
  232: "Longsleeve",
  233: "Longsleeve Buttonup",
  234: "Longsleeve Collared",
  235: "Tshirt",
  236: "Tshirt Collared",
  237: "Vest",
  238: "Vest Torn",
};
const OUTERWEAR = {
  239: "Dinner Jacket Open",
  240: "Hoodie",
  241: "Jacket Closed",
  242: "Jacket Elbowpatches Open",
  243: "Jacket Open",
  244: "Overalls",
  245: "Prisoners Robe",
  246: "Waistcoat",
};
const PRINTS = {
  247: "Banana",
  248: "Beer",
  249: "Bomb",
  250: "Burger",
  251: "Cactus",
  252: "Carrot",
  253: "Duck",
  254: "Heart",
  255: "Ice Cream",
  256: "Moon",
  257: "Number 15",
  258: "Number One",
  259: "Rock",
  260: "Skull",
  261: "Smile",
  262: "Sun",
};
const BOTTOMS = {
  263: "Boxers",
  264: "Boxers Dotty",
  265: "Boxers Striped",
  266: "Briefs",
  267: "Dark Pants",
  268: "G String",
  269: "Jeans",
  270: "Jeans Kneepads",
  271: "Jorts",
  272: "Jorts Frayed",
  273: "Skirt",
  274: "Vertical Stripe Pants",
};
const FOOTWEAR = {
  275: "Shoes",
  276: "Shoes Basic",
  277: "Shoes Duck Faces",
  278: "Shoes Space Boots",
  279: "Shoes Work Boots",
};
const BELTS = { 280: "Belt Simple", 281: "Striped Belt", 282: "Studded Belt" };
const HATS = {
  283: "Baseball Cap 01",
  284: "Baseball Cap 02",
  285: "Baseball Cap 03",
  286: "Baseball Cap 04",
  287: "Baseball Cap 05",
  288: "Baseball Cap 06",
  289: "Baseball Cap 07",
  290: "Beanie",
  291: "Bowler Hat",
  292: "Construction Helmet",
  293: "Cowboy Hat",
  294: "Crown",
  295: "Fish Hat",
  296: "Hamburger",
  297: "Helmet Viking",
  298: "Kid Propeller Hat",
  299: "Party Hat",
  300: "Pirate Hat",
  301: "Police Hat",
  302: "Santa Hat",
  303: "Sombrero",
  304: "Top Hat",
  305: "Traffic Cone",
};
const EYEWEAR = {
  306: "Broken Glasses",
  307: "Cyborg",
  308: "Eyepatch",
  309: "Eyepatch Skull",
  310: "Goggles Vr",
  311: "Monacle",
  312: "Party Glasses",
  313: "Rectangular Glasses",
  314: "Steampunk Goggles",
  315: "Sunglasses 01",
  316: "Sunglasses 02",
  317: "Sunglasses 03",
  318: "Sunglasses 04",
  319: "Visor",
};
const PIERCINGS = { 320: "Earring" };
const WRISTS = { 321: "Sweatband", 322: "Watch" };
const HANDS = { 323: "Gloves", 324: "Gloves Cooking" };
const NECKWEAR = { 325: "Bowtie", 326: "Necklace Gold", 327: "Tie" };
const LEFT_ITEMS = { 328: "Hold Left Briefcase", 329: "Hold Left Dynamite" };
const RIGHT_ITEMS = {
  330: "Hold Right Big Sword",
  331: "Hold Right Cutlass",
  332: "Hold Right Guitar",
  333: "Hold Right Keyboard",
  334: "Hold Right Lifesaver Ring",
  335: "Hold Right Sword",
  336: "Hold Right Umbrella",
};

const TRAIT_VALUE_MAP = {
  ...TRIBES,
  ...SKIN_COLORS,
  ...FUR_COLORS,
  ...EYE_COLORS,
  ...PUPIL_COLORS,
  ...HAIR,
  ...MOUTHS,
  ...BEARDS,
  ...FACEMARKS,
  ...MISC,
  ...TOPS,
  ...OUTERWEAR,
  ...PRINTS,
  ...BOTTOMS,
  ...FOOTWEAR,
  ...BELTS,
  ...HATS,
  ...EYEWEAR,
  ...PIERCINGS,
  ...WRISTS,
  ...HANDS,
  ...NECKWEAR,
  ...LEFT_ITEMS,
  ...RIGHT_ITEMS,
};

module.exports = { CHARACTER_TRAIT_TYPES, TRAIT_VALUE_MAP };
